[package]
name = "bridge-proxy"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]
doctest = false

[dependencies]
soroban-sdk = { workspace = true }
arrayref = "0.3.9"

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
